### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by jannickj** [lierdakil/haskell-ghc-mod#1]
When I have ide-haskell running I get this error every time I save the my files. :S

1. Save file

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.3.1

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:85

Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:282:12)
  at GhcModiProcess.module.exports.GhcModiProcess.runCmd (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:33:22)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:94:8
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:61:9
  at c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\temp\lib\temp.js:150:7
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:03.8 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "C:\\Users\\jannick\\Projects"
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.1.2
autocomplete-plus, v2.0.3
haskell-ghc-mod, v0.3.1
ide-haskell, v0.3.0
language-haskell, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jannickj** [comment]
nevermind has nothing todo with ide-haskell just tested it :p

**Comment by lierdakil** [comment]
Okay, I never tested on Windows, but it seems that ghc-modi process abruptly stops when it gets command to check file for errors. I can't reproduce this error on linux (for now), so I will likely have to rely on your help in tracking this down.

For the time being, let me ask if any of other ghc-mod-haskell functions work as expected, e.g. get type/info under cursor (default shortcuts are ctrl+alt+t and ctrl+alt+i respectively)? Does this happen with any file or just some?

**Comment by jannickj** [comment]
Ill perform some tests 2 min

**Comment by jannickj** [comment]
Ok i did some test to be sure that what I am saying is correct. Basically none of the functionality works for me, however if I dont have haskell-ghc-mod running then autocomplete-haskell doesn't work either. I assumed it was a requirement but reading through it seems like pure coincidence.

when I press ctrl-alt-t i get
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:55

TypeError: undefined is not a function
  at atom-text-editor.subscriptions.add.atom.commands.add.haskell-ghc-mod:type (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\haskell-ghc-mod.coffee:55:56)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\window-event-handler.js:170:20)

```

however I think a more interesting error is when I load a file I get
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:53)
  at TextBuffer.module.exports.TextBuffer.clipRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:925:20)
  at MarkerManager._results.push._this.(anonymous function) [as clipRange] (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\delegato\lib\delegator.js:67:61)
  at MarkerManager.module.exports.MarkerManager.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\marker-manager.js:84:20)
  at TextBuffer.module.exports.TextBuffer.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:645:27)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\display-buffer.js:1274:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1290:59)
  at EditorController.module.exports.EditorController.showError (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:77:41)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:1:1
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:102:11
  at Array.forEach (native)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:95:15
  at Socket.<anonymous> (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:31:7)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

**Comment by jannickj** [comment]
I tried it on my laptop with arch linux and a fresh install.. using same files I get the same error. So i doubt its windows related.

**Comment by lierdakil** [comment]
Could you possibly run `ghc-mod check <file>` manually and post its output then? I might have a couple ideas, but they are a little fuzzy for now.

**Comment by jannickj** [comment]
windows:
jannick@***** ~/P/hs-learning> ghc-mod check src/PDDL/Logic.hs
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:3:1:Warning: The qualifie                                                                                           d import of `Data.List' is redundant  except perhaps to import instances from `D                                                                                           ata.List'To import instances alone, use: import Data.List()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:5:1:Warning: The qualifie                                                                                           d import of `Data.Set' is redundant  except perhaps to import instances from `Da                                                                                           ta.Set'To import instances alone, use: import Data.Set()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:14:Warning: Defined bu                                                                                           t not used: `action'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:21:Warning: Defined bu                                                                                           t not used: `oldState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:30:Warning: Defined bu                                                                                           t not used: `internalState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:44:Warning: Defined bu                                                                                           t not used: `actualState'
src\PDDL\Logic.hs:7:1:Warning: The import of `Data.Set' is redundant  except per                                                                                           haps to import instances from `Data.Set'To import instances alone, use: import D                                                                                           ata.Set()
src\PDDL\Logic.hs:23:20:Warning: Defined but not used: `s'
src\PDDL\Logic.hs:37:37:Warning: Defined but not used: `posEff'
src\PDDL\Logic.hs:37:44:Warning: Defined but not used: `negEff'

**Comment by jannickj** [comment]
however my project is on github: https://github.com/srnjcbsn/hs-learning.git

**Comment by lierdakil** [comment]
It does not crash for me on your project. I've pushed v0.3.2, which should handle error reporting a little better. This may give some insight to what is actually happening. Thank you for helping with this by the way.

**Comment by jannickj** [comment]
hmmm it seemes the updated output caught the error, as I expected it was a bit of my own doing, I dont use hspec-disover as I just run cabal test 

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.3.2

### Stack Trace

Uncaught Error: Ghc-modi terminated:
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:3:1:Warning: The qualified import of `Data.List' is redundant
  except perhaps to import instances from `Data.List'
To import instances alone, use: import Data.List()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:5:1:Warning: The qualified import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:14:Warning: Defined but not used: `action'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:21:Warning: Defined but not used: `oldState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:30:Warning: Defined but not used: `internalState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:44:Warning: Defined but not used: `actualState'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:3:1:Warning: The import of `Control.Monad' is redundant
  except perhaps to import instances from `Control.Monad'
To import instances alone, use: import Control.Monad()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:9:8:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:15:17:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:23:1:Warning: Top-level binding with no type signature:
  parseConstant :: Parser String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:25:1:Warning: Top-level binding with no type signature:
  parseArgRef :: Text.Parsec.Prim.ParsecT
                   String
                   ()
                   transformers-0.3.0.0:Data.Functor.Identity.Identity
                   String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:41:1:Warning: Top-level binding with no type signature:
  parseFluent :: Parser (String, [Argument])
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:48:1:Warning: Top-level binding with no type signature:
  parseConjunction :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:54:1:Warning: Top-level binding with no type signature:
  parseNegation :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:91:9:Warning: Defined but not used: `name'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:109:9:Warning: This binding for `dom' shadows the existing binding
  imported from `PDDL.Type' at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:4:1-26
  (and originally defined
     at C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:70:1-3)
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:109:9:Warning: Defined but not used: `dom'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:111:9:Warning: Defined but not used: `objs'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:122:1:Warning: Top-level binding with no type signature:
  doParse :: forall s a t.
             Text.Parsec.Prim.Stream
               s transformers-0.3.0.0:Data.Functor.Identity.Identity t =>
             Text.Parsec.Prim.Parsec s () a -> s -> Either ParseError a
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1:Warning: Top-level binding with no type signature:
  p :: String -> Either ParseError Domain
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:34:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char '('
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:38:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char ')'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:69:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":action "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:72:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":parameters "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:75:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":precondition "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:78:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":effect "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:90:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:106:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
OK
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:7:1:Warning: The import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:23:20:Warning: Defined but not used: `s'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:37:37:Warning: Defined but not used: `posEff'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:37:44:Warning: Defined but not used: `negEff'
OK
NG BUG: ghc-modi: could not execute: hspec-discover


```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:59

Error: Ghc-modi terminated:
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:3:1:Warning: The qualified import of `Data.List' is redundant
  except perhaps to import instances from `Data.List'
To import instances alone, use: import Data.List()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:5:1:Warning: The qualified import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:14:Warning: Defined but not used: `action'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:21:Warning: Defined but not used: `oldState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:30:Warning: Defined but not used: `internalState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:44:Warning: Defined but not used: `actualState'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:3:1:Warning: The import of `Control.Monad' is redundant
  except perhaps to import instances from `Control.Monad'
To import instances alone, use: import Control.Monad()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:9:8:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:15:17:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:23:1:Warning: Top-level binding with no type signature:
  parseConstant :: Parser String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:25:1:Warning: Top-level binding with no type signature:
  parseArgRef :: Text.Parsec.Prim.ParsecT
                   String
                   ()
                   transformers-0.3.0.0:Data.Functor.Identity.Identity
                   String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:41:1:Warning: Top-level binding with no type signature:
  parseFluent :: Parser (String, [Argument])
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:48:1:Warning: Top-level binding with no type signature:
  parseConjunction :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:54:1:Warning: Top-level binding with no type signature:
  parseNegation :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:91:9:Warning: Defined but not used: `name'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:109:9:Warning: This binding for `dom' shadows the existing binding
  imported from `PDDL.Type' at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:4:1-26
  (and originally defined
     at C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:70:1-3)
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:109:9:Warning: Defined but not used: `dom'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:111:9:Warning: Defined but not used: `objs'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:122:1:Warning: Top-level binding with no type signature:
  doParse :: forall s a t.
             Text.Parsec.Prim.Stream
               s transformers-0.3.0.0:Data.Functor.Identity.Identity t =>
             Text.Parsec.Prim.Parsec s () a -> s -> Either ParseError a
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:144:1:Warning: Top-level binding with no type signature:
  p :: String -> Either ParseError Domain
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:34:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char '('
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:38:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char ')'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:69:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":action "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:72:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":parameters "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:75:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":precondition "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:78:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":effect "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:90:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-1ngujyd.hs:106:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
OK
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:7:1:Warning: The import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:23:20:Warning: Defined but not used: `s'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:37:37:Warning: Defined but not used: `posEff'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-7352-tw01nf.hs:37:44:Warning: Defined but not used: `negEff'
OK
NG BUG: ghc-modi: could not execute: hspec-discover

  at Socket.<anonymous> (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:36:17)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

**Comment by jannickj** [comment]
nevermind what I said, i had it installed but just only in my sandbox :p

**Comment by lierdakil** [comment]
Okay, so basically problem is there is no support for cabal sandboxes, right? There is really none, that much is true. Let me try to hack in something for the time being, until I get to doing it properly.

**Comment by jannickj** [comment]
Nice thx :>

**Comment by jannickj** [comment]
a dirty hack would be to try and test if /home/jannick/Projects/hs-learning/.cabal-sandbox/hspec-discover exists. IE. "project path"/.cabal-sandbox/"program"

**Comment by lierdakil** [comment]
Easier to add "project path"/.cabal-sandbox/bin to PATH, really. But PATH format differs between platforms, so I need a little time to sort this out.

**Comment by lierdakil** [comment]
Okay, I pushed out v0.3.3. Not sure it will help though, but it should search cabal sandbox first (it could even have project-specific ghc-mod installation)

**Comment by jannickj** [comment]
Thanks alot :) It still itsn't working though :/ But atleast its not an execution error anymore.

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.3.3

### Stack Trace

Uncaught Error: Ghc-modi terminated:
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:3:1:Warning: The qualified import of `Data.List' is redundant
  except perhaps to import instances from `Data.List'
To import instances alone, use: import Data.List()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:5:1:Warning: The qualified import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:14:Warning: Defined but not used: `action'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:21:Warning: Defined but not used: `oldState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:30:Warning: Defined but not used: `internalState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:44:Warning: Defined but not used: `actualState'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:3:1:Warning: The import of `Control.Monad' is redundant
  except perhaps to import instances from `Control.Monad'
To import instances alone, use: import Control.Monad()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:9:8:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:15:17:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:23:1:Warning: Top-level binding with no type signature:
  parseConstant :: Parser String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:25:1:Warning: Top-level binding with no type signature:
  parseArgRef :: Text.Parsec.Prim.ParsecT
                   String
                   ()
                   transformers-0.3.0.0:Data.Functor.Identity.Identity
                   String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:41:1:Warning: Top-level binding with no type signature:
  parseFluent :: Parser (String, [Argument])
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:48:1:Warning: Top-level binding with no type signature:
  parseConjunction :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:54:1:Warning: Top-level binding with no type signature:
  parseNegation :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:91:9:Warning: Defined but not used: `name'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:109:9:Warning: This binding for `dom' shadows the existing binding
  imported from `PDDL.Type' at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:4:1-26
  (and originally defined
     at C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:70:1-3)
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:109:9:Warning: Defined but not used: `dom'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:111:9:Warning: Defined but not used: `objs'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:122:1:Warning: Top-level binding with no type signature:
  doParse :: forall s a t.
             Text.Parsec.Prim.Stream
               s transformers-0.3.0.0:Data.Functor.Identity.Identity t =>
             Text.Parsec.Prim.Parsec s () a -> s -> Either ParseError a
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1:Warning: Top-level binding with no type signature:
  p :: String -> Either ParseError Domain
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:34:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char '('
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:38:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char ')'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:69:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":action "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:72:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":parameters "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:75:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":precondition "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:78:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":effect "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:90:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:106:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
OK


```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:68

Error: Ghc-modi terminated:
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:3:1:Warning: The qualified import of `Data.List' is redundant
  except perhaps to import instances from `Data.List'
To import instances alone, use: import Data.List()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:5:1:Warning: The qualified import of `Data.Set' is redundant
  except perhaps to import instances from `Data.Set'
To import instances alone, use: import Data.Set()
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:14:Warning: Defined but not used: `action'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:21:Warning: Defined but not used: `oldState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:30:Warning: Defined but not used: `internalState'
C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:93:44:Warning: Defined but not used: `actualState'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:3:1:Warning: The import of `Control.Monad' is redundant
  except perhaps to import instances from `Control.Monad'
To import instances alone, use: import Control.Monad()
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:9:8:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:15:17:Warning: This binding for `p' shadows the existing binding
  defined at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:23:1:Warning: Top-level binding with no type signature:
  parseConstant :: Parser String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:25:1:Warning: Top-level binding with no type signature:
  parseArgRef :: Text.Parsec.Prim.ParsecT
                   String
                   ()
                   transformers-0.3.0.0:Data.Functor.Identity.Identity
                   String
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:41:1:Warning: Top-level binding with no type signature:
  parseFluent :: Parser (String, [Argument])
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:48:1:Warning: Top-level binding with no type signature:
  parseConjunction :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:54:1:Warning: Top-level binding with no type signature:
  parseNegation :: Parser Formula
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:91:9:Warning: Defined but not used: `name'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:109:9:Warning: This binding for `dom' shadows the existing binding
  imported from `PDDL.Type' at C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:4:1-26
  (and originally defined
     at C:\Users\jannick\Projects\hs-learning\src\PDDL\Type.hs:70:1-3)
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:109:9:Warning: Defined but not used: `dom'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:111:9:Warning: Defined but not used: `objs'
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:122:1:Warning: Top-level binding with no type signature:
  doParse :: forall s a t.
             Text.Parsec.Prim.Stream
               s transformers-0.3.0.0:Data.Functor.Identity.Identity t =>
             Text.Parsec.Prim.Parsec s () a -> s -> Either ParseError a
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:144:1:Warning: Top-level binding with no type signature:
  p :: String -> Either ParseError Domain
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:34:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char '('
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:38:5:Warning: A do-notation statement discarded a result of type `Char'
Suppress this warning by saying _ <- char ')'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:69:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":action "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:72:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":parameters "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:75:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":precondition "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:78:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string ":effect "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:90:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
C:\Users\jannick\AppData\Local\Temp\haskell-ghc-mod115031-6088-1gipc6c.hs:106:9:Warning: A do-notation statement discarded a result of type `String'
Suppress this warning by saying `_ <- string "define "'
or by using the flag -fno-warn-unused-do-bind
OK

  at Socket.<anonymous> (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:43:17)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "merge-conflicts",
      "ide-haskell",
      "autocomplete-haskell",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "C:\\Users\\jannick\\Projects"
  },
  "haskell-ghc-mod": {
    "ghcModiPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-modi",
    "ghcModPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-mod"
  }
}
```

### Installed Packages

```coffee
# User
haskell-ghc-mod, v0.3.3
language-haskell, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lierdakil** [comment]
That's probably my fault. I keep forgetting about pesky win32 newlines. Try v0.3.4

**Comment by lierdakil** [comment]
So, can we close this one?

**Comment by jannickj** [comment]
Sorry I fell asleep I was super tired ;)
I am still getting errors: 
on windows i get these on load (No errors on arch linux)
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:53)
  at TextBuffer.module.exports.TextBuffer.clipRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:925:20)
  at MarkerManager._results.push._this.(anonymous function) [as clipRange] (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\delegato\lib\delegator.js:67:61)
  at MarkerManager.module.exports.MarkerManager.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\marker-manager.js:84:20)
  at TextBuffer.module.exports.TextBuffer.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:645:27)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\display-buffer.js:1274:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1290:59)
  at EditorController.module.exports.EditorController.showError (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:77:41)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:1:1
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:127:11
  at Array.forEach (native)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:120:15
  at Socket.<anonymous> (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:54:9)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)
```
### Stack Trace

Uncaught Error: Ghc-modi terminated:
NG BUG: ghc-modi: phase `Haskell pre-processor' failed (exitcode = 1)

```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:88

Error: Ghc-modi terminated:
NG BUG: ghc-modi: phase `Haskell pre-processor' failed (exitcode = 1)
  at Socket.<anonymous> (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:51:19)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```
And when i use ctrl-alt-t on either windows or arch linux i get:

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:60

TypeError: undefined is not a function
  at atom-text-editor.subscriptions.add.atom.commands.add.haskell-ghc-mod:type (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\haskell-ghc-mod.coffee:60:56)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\window-event-handler.js:170:20)

```

**Comment by lierdakil** [comment]
Ok, let us try something first. What happens if you uncheck `Enable Ghc Modi` in ghc-mod-haskell settings and restart Atom (ctrl+alt+r)?

**Comment by jannickj** [comment]
On windows i get:
**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.3.6

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:943:53)
  at TextBuffer.module.exports.TextBuffer.clipRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:925:20)
  at MarkerManager._results.push._this.(anonymous function) [as clipRange] (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\delegato\lib\delegator.js:67:61)
  at MarkerManager.module.exports.MarkerManager.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\marker-manager.js:84:20)
  at TextBuffer.module.exports.TextBuffer.markRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:645:27)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\display-buffer.js:1274:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1290:59)
  at EditorController.module.exports.EditorController.showError (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:77:41)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\editor-controller.coffee:1:1
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:127:11
  at Array.forEach (native)
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:120:15
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:44:9
  at c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:62:7
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1009:16)
  at Socket.<anonymous> (child_process.js:1177:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:469:12)

```

### Commands

```
     -0:01.0 haskell-ghc-mod:type (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "merge-conflicts",
      "ide-haskell",
      "autocomplete-haskell",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "C:\\Users\\jannick\\Projects"
  },
  "haskell-ghc-mod": {
    "ghcModPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-mod",
    "enableGhcModi": false,
    "ghcModiPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-modi"
  }
}
```

### Installed Packages

```coffee
# User
haskell-ghc-mod, v0.3.6
language-haskell, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jannickj** [comment]
and when I press ctrl-alt-t i get(same for archlinux):

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.3.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/jannick/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:60

TypeError: undefined is not a function
  at atom-text-editor.subscriptions.add.atom.commands.add.haskell-ghc-mod:type (c:\Users\jannick\.atom\packages\haskell-ghc-mod\lib\haskell-ghc-mod.coffee:60:56)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\jannick\AppData\Local\atom\app-0.176.0\resources\app\src\window-event-handler.js:170:20)

```

### Commands

```
     -0:03.7 haskell-ghc-mod:type (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "merge-conflicts",
      "ide-haskell",
      "autocomplete-haskell",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "C:\\Users\\jannick\\Projects"
  },
  "haskell-ghc-mod": {
    "ghcModPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-mod",
    "enableGhcModi": false,
    "ghcModiPath": "C:\\Users\\jannick\\AppData\\Roaming\\cabal\\bin\\ghc-modi"
  }
}
```

### Installed Packages

```coffee
# User
haskell-ghc-mod, v0.3.6
language-haskell, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jannickj** [comment]
are you running the same version of atom as me?

**Comment by lierdakil** [comment]
Good point, apparently I'm not. Hold on.

**Comment by lierdakil** [comment]
Ok, I think I understand what's the deal with windows-specific error. I will try to fix this shortly.

**Comment by lierdakil** [comment]
Windows-specific one should be solved by v0.3.7. As for other one, I'm really quite stumped. I have no idea why this is happening, and can't reproduce it neither on Win, nor on Linux. Updating Atom  changed nothing as well (0.174 vs 0.176).

**Comment by jannickj** [comment]
ok thanks for trying though. also your update did fix the length error :)

**Comment by jannickj** [comment]
Just a question is there a dependency between haskell-ghc-mod and autocomplete-haskell because autocomplete-haskell doesn't work unless I have haskell-ghc-mod installed.

**Comment by lierdakil** [comment]
There is, it says so in the readme. I opted for more modular approach with this packages, to avoid implementing same logic twice. Is that disagreeable?

**Comment by lierdakil** [comment]
Anyway, ide-haskell actually provides autocompletion with ac-plus. It is not maintained lately, however, so some things are broken (primarily cosmetic stuff for the moment), but using h-g-m, ac-haskell and ide-haskell all together is a little bit of overkill, I think.
Btw, linter-hlint provides great linting support (better than that of ide-haskell, I think), if you want that.

**Comment by jannickj** [comment]
Honestly I think you should just add it as a submodule to autocomplete-haskell or at the very least make it throw an error msg. Also the problem of having haskell-ghc-mod be a library and a real plugin is that it forces one to have both mods if all one wanted was just the autocomplete-haskell mod.

**Comment by jannickj** [comment]
yes i agree but all I want is autocomplete and ide-haskell but ide-haskell autocomplete is broken, which forces me to either A: learn coffe and fix it myself or B: run all 3 mods :)

**Comment by lierdakil** [comment]
Problem is, at the moment atom does not allow to specify inter-package dependencies. You might be right about, let's say, excessive functionality. But truthfully, unchecking all options in h-g-m settings will disable most of it. I could probably disable the rest if all checkboxes are ticked off. Well, except hotkeys (but those could be disabled in user config)

**Comment by jannickj** [comment]
Sucks :( Anyway I think we can close this issue the mod doesn't crash when I save anymore which was the original issue ^^

**Comment by lierdakil** [comment]
Ok, closing this as resolved. If you ever decide to use more of this packages' features, and the bug still persists, feel free to open a new issue.
